sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t bhandarikaran1995/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true bhandarikaran1995/react-test npm run test
  
after_success:
  - docker build -t bhandarikaran1995/multi-client ./client
  - docker build -t bhandarikaran1995/multi-nginx ./nginx
  - docker build -t bhandarikaran1995/multi-server ./server
  - docker build -t bhandarikaran1995/multi-worker ./worker  

  #login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push them to docker hub

  - docker push bhandarikaran1995/multi-client
  - docker push bhandarikaran1995/multi-nginx
  - docker push bhandarikaran1995/multi-server
  - docker push bhandarikaran1995/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-356095541420'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY